# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import omnnii_pb2 as omnnii__pb2


class OmniiServiceStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.Enroll = channel.unary_unary(
        '/omnii.OmniiService/Enroll',
        request_serializer=omnnii__pb2.EnrollRequest.SerializeToString,
        response_deserializer=omnnii__pb2.EnrollResponse.FromString,
        )
    self.RefreshToken = channel.unary_unary(
        '/omnii.OmniiService/RefreshToken',
        request_serializer=omnnii__pb2.RefreshTokenRequest.SerializeToString,
        response_deserializer=omnnii__pb2.RefreshTokenResponse.FromString,
        )
    self.Heartbeat = channel.unary_unary(
        '/omnii.OmniiService/Heartbeat',
        request_serializer=omnnii__pb2.HeartbeatRequest.SerializeToString,
        response_deserializer=omnnii__pb2.HeartbeatResponse.FromString,
        )
    self.ReportUpdates = channel.unary_unary(
        '/omnii.OmniiService/ReportUpdates',
        request_serializer=omnnii__pb2.UpdateReportRequest.SerializeToString,
        response_deserializer=omnnii__pb2.UpdateReportResponse.FromString,
        )
    self.ReportStats = channel.unary_unary(
        '/omnii.OmniiService/ReportStats',
        request_serializer=omnnii__pb2.StatsReportRequest.SerializeToString,
        response_deserializer=omnnii__pb2.StatsReportResponse.FromString,
        )
    self.ReportConnectivity = channel.unary_unary(
        '/omnii.OmniiService/ReportConnectivity',
        request_serializer=omnnii__pb2.ConnectivityReportRequest.SerializeToString,
        response_deserializer=omnnii__pb2.ConnectivityReportResponse.FromString,
        )
    self.TriggerUpdate = channel.unary_unary(
        '/omnii.OmniiService/TriggerUpdate',
        request_serializer=omnnii__pb2.TriggerUpdateRequest.SerializeToString,
        response_deserializer=omnnii__pb2.TriggerUpdateResponse.FromString,
        )


class OmniiServiceServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def Enroll(self, request, context):
    """Enrollment - unauthenticated, only needs valid enrollment code
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def RefreshToken(self, request, context):
    """Refresh short-lived access tokens
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def Heartbeat(self, request, context):
    """All methods below require token authentication via metadata
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def ReportUpdates(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def ReportStats(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def ReportConnectivity(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def TriggerUpdate(self, request, context):
    """Trigger an update on the addon (server -> addon request)
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_OmniiServiceServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'Enroll': grpc.unary_unary_rpc_method_handler(
          servicer.Enroll,
          request_deserializer=omnnii__pb2.EnrollRequest.FromString,
          response_serializer=omnnii__pb2.EnrollResponse.SerializeToString,
      ),
      'RefreshToken': grpc.unary_unary_rpc_method_handler(
          servicer.RefreshToken,
          request_deserializer=omnnii__pb2.RefreshTokenRequest.FromString,
          response_serializer=omnnii__pb2.RefreshTokenResponse.SerializeToString,
      ),
      'Heartbeat': grpc.unary_unary_rpc_method_handler(
          servicer.Heartbeat,
          request_deserializer=omnnii__pb2.HeartbeatRequest.FromString,
          response_serializer=omnnii__pb2.HeartbeatResponse.SerializeToString,
      ),
      'ReportUpdates': grpc.unary_unary_rpc_method_handler(
          servicer.ReportUpdates,
          request_deserializer=omnnii__pb2.UpdateReportRequest.FromString,
          response_serializer=omnnii__pb2.UpdateReportResponse.SerializeToString,
      ),
      'ReportStats': grpc.unary_unary_rpc_method_handler(
          servicer.ReportStats,
          request_deserializer=omnnii__pb2.StatsReportRequest.FromString,
          response_serializer=omnnii__pb2.StatsReportResponse.SerializeToString,
      ),
      'ReportConnectivity': grpc.unary_unary_rpc_method_handler(
          servicer.ReportConnectivity,
          request_deserializer=omnnii__pb2.ConnectivityReportRequest.FromString,
          response_serializer=omnnii__pb2.ConnectivityReportResponse.SerializeToString,
      ),
      'TriggerUpdate': grpc.unary_unary_rpc_method_handler(
          servicer.TriggerUpdate,
          request_deserializer=omnnii__pb2.TriggerUpdateRequest.FromString,
          response_serializer=omnnii__pb2.TriggerUpdateResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'omnii.OmniiService', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
