# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import omnnii_pb2 as omnnii__pb2


class OmniiServiceStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.Enroll = channel.unary_unary(
        '/omnii.OmniiService/Enroll',
        request_serializer=omnnii__pb2.EnrollRequest.SerializeToString,
        response_deserializer=omnnii__pb2.EnrollResponse.FromString,
        )
    self.Handshake = channel.unary_unary(
        '/omnii.OmniiService/Handshake',
        request_serializer=omnnii__pb2.HandshakeRequest.SerializeToString,
        response_deserializer=omnnii__pb2.HandshakeResponse.FromString,
        )
    self.Heartbeat = channel.unary_unary(
        '/omnii.OmniiService/Heartbeat',
        request_serializer=omnnii__pb2.HeartbeatRequest.SerializeToString,
        response_deserializer=omnnii__pb2.HeartbeatResponse.FromString,
        )
    self.ReportUpdates = channel.unary_unary(
        '/omnii.OmniiService/ReportUpdates',
        request_serializer=omnnii__pb2.UpdateReportRequest.SerializeToString,
        response_deserializer=omnnii__pb2.UpdateReportResponse.FromString,
        )
    self.TriggerUpdate = channel.unary_unary(
        '/omnii.OmniiService/TriggerUpdate',
        request_serializer=omnnii__pb2.TriggerUpdateRequest.SerializeToString,
        response_deserializer=omnnii__pb2.TriggerUpdateResponse.FromString,
        )


class OmniiServiceServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def Enroll(self, request, context):
    """Enrollment - unauthenticated, only needs valid enrollment code
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def Handshake(self, request, context):
    """All methods below require token authentication
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def Heartbeat(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def ReportUpdates(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def TriggerUpdate(self, request, context):
    """Trigger an update on the addon (server -> addon request)
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_OmniiServiceServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'Enroll': grpc.unary_unary_rpc_method_handler(
          servicer.Enroll,
          request_deserializer=omnnii__pb2.EnrollRequest.FromString,
          response_serializer=omnnii__pb2.EnrollResponse.SerializeToString,
      ),
      'Handshake': grpc.unary_unary_rpc_method_handler(
          servicer.Handshake,
          request_deserializer=omnnii__pb2.HandshakeRequest.FromString,
          response_serializer=omnnii__pb2.HandshakeResponse.SerializeToString,
      ),
      'Heartbeat': grpc.unary_unary_rpc_method_handler(
          servicer.Heartbeat,
          request_deserializer=omnnii__pb2.HeartbeatRequest.FromString,
          response_serializer=omnnii__pb2.HeartbeatResponse.SerializeToString,
      ),
      'ReportUpdates': grpc.unary_unary_rpc_method_handler(
          servicer.ReportUpdates,
          request_deserializer=omnnii__pb2.UpdateReportRequest.FromString,
          response_serializer=omnnii__pb2.UpdateReportResponse.SerializeToString,
      ),
      'TriggerUpdate': grpc.unary_unary_rpc_method_handler(
          servicer.TriggerUpdate,
          request_deserializer=omnnii__pb2.TriggerUpdateRequest.FromString,
          response_serializer=omnnii__pb2.TriggerUpdateResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'omnii.OmniiService', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
