# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import omnnii_pb2 as omnnii__pb2

GRPC_GENERATED_VERSION = '1.68.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in omnnii_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class OmniiServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Enroll = channel.unary_unary(
                '/omnii.OmniiService/Enroll',
                request_serializer=omnnii__pb2.EnrollRequest.SerializeToString,
                response_deserializer=omnnii__pb2.EnrollResponse.FromString,
                _registered_method=True)
        self.RefreshToken = channel.unary_unary(
                '/omnii.OmniiService/RefreshToken',
                request_serializer=omnnii__pb2.RefreshTokenRequest.SerializeToString,
                response_deserializer=omnnii__pb2.RefreshTokenResponse.FromString,
                _registered_method=True)
        self.Heartbeat = channel.unary_unary(
                '/omnii.OmniiService/Heartbeat',
                request_serializer=omnnii__pb2.HeartbeatRequest.SerializeToString,
                response_deserializer=omnnii__pb2.HeartbeatResponse.FromString,
                _registered_method=True)
        self.ReportUpdates = channel.unary_unary(
                '/omnii.OmniiService/ReportUpdates',
                request_serializer=omnnii__pb2.UpdateReportRequest.SerializeToString,
                response_deserializer=omnnii__pb2.UpdateReportResponse.FromString,
                _registered_method=True)
        self.ReportStats = channel.unary_unary(
                '/omnii.OmniiService/ReportStats',
                request_serializer=omnnii__pb2.StatsReportRequest.SerializeToString,
                response_deserializer=omnnii__pb2.StatsReportResponse.FromString,
                _registered_method=True)
        self.TriggerUpdate = channel.unary_unary(
                '/omnii.OmniiService/TriggerUpdate',
                request_serializer=omnnii__pb2.TriggerUpdateRequest.SerializeToString,
                response_deserializer=omnnii__pb2.TriggerUpdateResponse.FromString,
                _registered_method=True)


class OmniiServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Enroll(self, request, context):
        """Enrollment - unauthenticated, only needs valid enrollment code
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RefreshToken(self, request, context):
        """Refresh short-lived access tokens
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Heartbeat(self, request, context):
        """All methods below require token authentication via metadata
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReportUpdates(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReportStats(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def TriggerUpdate(self, request, context):
        """Trigger an update on the addon (server -> addon request)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_OmniiServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Enroll': grpc.unary_unary_rpc_method_handler(
                    servicer.Enroll,
                    request_deserializer=omnnii__pb2.EnrollRequest.FromString,
                    response_serializer=omnnii__pb2.EnrollResponse.SerializeToString,
            ),
            'RefreshToken': grpc.unary_unary_rpc_method_handler(
                    servicer.RefreshToken,
                    request_deserializer=omnnii__pb2.RefreshTokenRequest.FromString,
                    response_serializer=omnnii__pb2.RefreshTokenResponse.SerializeToString,
            ),
            'Heartbeat': grpc.unary_unary_rpc_method_handler(
                    servicer.Heartbeat,
                    request_deserializer=omnnii__pb2.HeartbeatRequest.FromString,
                    response_serializer=omnnii__pb2.HeartbeatResponse.SerializeToString,
            ),
            'ReportUpdates': grpc.unary_unary_rpc_method_handler(
                    servicer.ReportUpdates,
                    request_deserializer=omnnii__pb2.UpdateReportRequest.FromString,
                    response_serializer=omnnii__pb2.UpdateReportResponse.SerializeToString,
            ),
            'ReportStats': grpc.unary_unary_rpc_method_handler(
                    servicer.ReportStats,
                    request_deserializer=omnnii__pb2.StatsReportRequest.FromString,
                    response_serializer=omnnii__pb2.StatsReportResponse.SerializeToString,
            ),
            'TriggerUpdate': grpc.unary_unary_rpc_method_handler(
                    servicer.TriggerUpdate,
                    request_deserializer=omnnii__pb2.TriggerUpdateRequest.FromString,
                    response_serializer=omnnii__pb2.TriggerUpdateResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'omnii.OmniiService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('omnii.OmniiService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class OmniiService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Enroll(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/omnii.OmniiService/Enroll',
            omnnii__pb2.EnrollRequest.SerializeToString,
            omnnii__pb2.EnrollResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RefreshToken(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/omnii.OmniiService/RefreshToken',
            omnnii__pb2.RefreshTokenRequest.SerializeToString,
            omnnii__pb2.RefreshTokenResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Heartbeat(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/omnii.OmniiService/Heartbeat',
            omnnii__pb2.HeartbeatRequest.SerializeToString,
            omnnii__pb2.HeartbeatResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReportUpdates(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/omnii.OmniiService/ReportUpdates',
            omnnii__pb2.UpdateReportRequest.SerializeToString,
            omnnii__pb2.UpdateReportResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReportStats(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/omnii.OmniiService/ReportStats',
            omnnii__pb2.StatsReportRequest.SerializeToString,
            omnnii__pb2.StatsReportResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def TriggerUpdate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/omnii.OmniiService/TriggerUpdate',
            omnnii__pb2.TriggerUpdateRequest.SerializeToString,
            omnnii__pb2.TriggerUpdateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
